### ISSUE TITLE
Project seems to be incompatible with npm 2

### ISSUE THREAD

**Issue by martin-eq** [zeit/nextgram#2]
I'm getting this error for each files inside the Pages folder:

```
ERROR in ./pages/index.js
Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator" specified in "base" at 0, attempted to resolve relative to "/Users/martin-eq/workspace/nextgram/pages"
```

The app won't display on localhost:3000

**Comment by guilhermedecampo** [comment]
Everything working fine here @martin-eq. I just tried out! Super awesome.

Have you `npm i` in the root folder?

**Comment by martin-eq** [comment]
Yes, I did. Also, I deleted the node_modules folder and reinstalled the dependencies but it keeps failing. Maybe because I have `Node 4.4.0` and `npm 2`? I have those versions because they are required for my current project

**Comment by martin-eq** [comment]
I just upgraded to `Node v6.6.0` and `npm 3`. Deleted dependencies and reinstalled. It's working properly now.

I'll change the issue subject, if you are not interested in supporting `npm 2`, maybe you should add a compatibility comment on the Readme and close this issue.

**Comment by jamo** [comment]
btw, nvm could be helpful if you need to live with multiple node/npm versions:  https://github.com/creationix/nvm
