### ISSUE TITLE
Seems have something wrong when install dependecies

### ISSUE THREAD

**Issue by HOUCe** [zeit/nextgram#21]
Hey, thanks for reading.

But when I run "sudo npm install",
I got:

> 
> npm WARN next@2.1.0 requires a peer of react@^15.4.2 but none was installed.
> npm WARN next@2.1.0 requires a peer of react-dom@^15.4.2 but none was installed.
> npm WARN styled-jsx@0.5.7 requires a peer of react@^15.0 but none was installed.
> npm WARN redbox-react@1.3.6 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
> npm WARN redbox-react@1.3.6 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed.

For infos,
I got node version : node/7.6.0
System: Mac

**Comment by leo** [comment]
Fixed!
